# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: stream_message.proto for package 'stream'

require 'grpc'
require 'stream_message_pb'

module Stream
  module Message
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'stream.Message'

      rpc :ParseRequest, ::Stream::Request, stream(::Stream::Response)
    end

    Stub = Service.rpc_stub_class
  end
end
