# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("stream_message.proto", :syntax => :proto3) do
    add_message "stream.Request" do
      optional :message, :string, 1
    end
    add_message "stream.Response" do
      optional :message, :string, 1
    end
  end
end

module Stream
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("stream.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("stream.Response").msgclass
end
